;; GENERATED by bin/ingest.cljs from resources/valueflows/all_vf.ttl.
;; DO NOT EDIT BY HAND. Regenerate: nbb bin/ingest.cljs
;;
;; The vocabulary as portable source, so no host I/O is needed to read it.
;; resources/valueflows/vocabulary.edn is the same value.

(ns valueflows.data)

(def vocabulary
{:actions
 {:accept
  {:accountable-effect :notApplicable,
   :accounting-effect :notApplicable,
   :comment
   "In processes like repair or a new stage or testing, the same identified resource will appear in the output.",
   :contained-effect :notApplicable,
   :create-resource :notApplicable,
   :event-quantity :resource,
   :input-output :input,
   :label "accept",
   :location-effect :update,
   :onhand-effect :decrement,
   :pairs-with :modify,
   :stage-effect :notApplicable,
   :state-effect :update,
   :term-status "stable"},
  :cite
  {:accountable-effect :notApplicable,
   :accounting-effect :notApplicable,
   :comment
   "For example a design file, neither used nor consumed, the file remains available at all times.",
   :contained-effect :notApplicable,
   :create-resource :notApplicable,
   :event-quantity :resource,
   :input-output :input,
   :label "cite",
   :location-effect :notApplicable,
   :onhand-effect :notApplicable,
   :pairs-with :notApplicable,
   :stage-effect :notApplicable,
   :state-effect :update,
   :term-status "stable"},
  :combine
  {:accountable-effect :notApplicable,
   :accounting-effect :notApplicable,
   :comment
   "A resource is combined with other resources into a container resource.",
   :contained-effect :update,
   :create-resource :notApplicable,
   :event-quantity :resource,
   :input-output :input,
   :label "combine",
   :location-effect :notApplicable,
   :onhand-effect :decrement,
   :pairs-with :notApplicable,
   :stage-effect :notApplicable,
   :state-effect :update,
   :term-status "unstable"},
  :consume
  {:accountable-effect :notApplicable,
   :accounting-effect :decrement,
   :comment
   "The consumed ingredient goes into the process, after the process the ingredient is gone.",
   :contained-effect :notApplicable,
   :create-resource :notApplicable,
   :event-quantity :resource,
   :input-output :input,
   :label "consume",
   :location-effect :notApplicable,
   :onhand-effect :decrement,
   :pairs-with :notApplicable,
   :stage-effect :notApplicable,
   :state-effect :update,
   :term-status "stable"},
  :copy
  {:accountable-effect :new,
   :accounting-effect :incrementTo,
   :comment
   "Create a new version of the resource, without any change to the original.",
   :contained-effect :notApplicable,
   :create-resource :optionalTo,
   :event-quantity :resource,
   :input-output :notApplicable,
   :label "copy",
   :location-effect :new,
   :onhand-effect :incrementTo,
   :pairs-with :notApplicable,
   :stage-effect :notApplicable,
   :state-effect :updateTo,
   :term-status "unstable"},
  :deliverService
  {:accountable-effect :notApplicable,
   :accounting-effect :notApplicable,
   :comment
   "New service produced and delivered (a service implies that an agent actively receives the service).",
   :contained-effect :notApplicable,
   :create-resource :notApplicable,
   :event-quantity :resource,
   :input-output :outputInput,
   :label "deliver service",
   :location-effect :notApplicable,
   :onhand-effect :notApplicable,
   :pairs-with :notApplicable,
   :stage-effect :notApplicable,
   :state-effect :notApplicable,
   :term-status "stable"},
  :dropoff
  {:accountable-effect :notApplicable,
   :accounting-effect :notApplicable,
   :comment
   "Transported resource or person leaves the process; the same resource or person appeared in the input.",
   :contained-effect :notApplicable,
   :create-resource :notApplicable,
   :event-quantity :resource,
   :input-output :output,
   :label "dropoff",
   :location-effect :update,
   :onhand-effect :increment,
   :pairs-with :pickup,
   :stage-effect :update,
   :state-effect :update,
   :term-status "stable"},
  :lower
  {:accountable-effect :new,
   :accounting-effect :decrement,
   :comment
   "Adjusts a quantity down based on a beginning balance or inventory count.",
   :contained-effect :notApplicable,
   :create-resource :optional,
   :event-quantity :resource,
   :input-output :notApplicable,
   :label "lower",
   :location-effect :notApplicable,
   :onhand-effect :decrement,
   :pairs-with :notApplicable,
   :stage-effect :notApplicable,
   :state-effect :update,
   :term-status "stable"},
  :modify
  {:accountable-effect :notApplicable,
   :accounting-effect :notApplicable,
   :comment
   "In processes like repair or a new stage or testing, the same identified resource will appear in the input.",
   :contained-effect :notApplicable,
   :create-resource :notApplicable,
   :event-quantity :resource,
   :input-output :output,
   :label "modify",
   :location-effect :update,
   :onhand-effect :increment,
   :pairs-with :accept,
   :stage-effect :update,
   :state-effect :update,
   :term-status "stable"},
  :move
  {:accountable-effect :notApplicable,
   :accounting-effect :decrementIncrement,
   :comment
   "Change location and possibly identifier, if location is part of the identification, of a resource with no change of agent rights or possession.",
   :contained-effect :notApplicable,
   :create-resource :optionalTo,
   :event-quantity :resource,
   :input-output :notApplicable,
   :label "move",
   :location-effect :updateTo,
   :onhand-effect :decrementIncrement,
   :pairs-with :notApplicable,
   :stage-effect :notApplicable,
   :state-effect :updateTo,
   :term-status "testing"},
  :pickup
  {:accountable-effect :notApplicable,
   :accounting-effect :notApplicable,
   :comment
   "Transported resource or person enters the process; the same resource will appear in the output.",
   :contained-effect :notApplicable,
   :create-resource :notApplicable,
   :event-quantity :resource,
   :input-output :input,
   :label "pickup",
   :location-effect :update,
   :onhand-effect :decrement,
   :pairs-with :dropoff,
   :stage-effect :notApplicable,
   :state-effect :update,
   :term-status "stable"},
  :produce
  {:accountable-effect :new,
   :accounting-effect :increment,
   :comment
   "New resource was created in that process or an existing stock resource was added to.",
   :contained-effect :notApplicable,
   :create-resource :optional,
   :event-quantity :resource,
   :input-output :output,
   :label "produce",
   :location-effect :new,
   :onhand-effect :increment,
   :pairs-with :notApplicable,
   :stage-effect :update,
   :state-effect :update,
   :term-status "stable"},
  :raise
  {:accountable-effect :new,
   :accounting-effect :increment,
   :comment
   "Adjusts a quantity up based on a beginning balance or inventory count.",
   :contained-effect :notApplicable,
   :create-resource :optional,
   :event-quantity :resource,
   :input-output :notApplicable,
   :label "raise",
   :location-effect :notApplicable,
   :onhand-effect :increment,
   :pairs-with :notApplicable,
   :stage-effect :notApplicable,
   :state-effect :update,
   :term-status "stable"},
  :separate
  {:accountable-effect :notApplicable,
   :accounting-effect :notApplicable,
   :comment "A resource is removed from a container resource.",
   :contained-effect :remove,
   :create-resource :notApplicable,
   :event-quantity :resource,
   :input-output :output,
   :label "unpack",
   :location-effect :notApplicable,
   :onhand-effect :increment,
   :pairs-with :notApplicable,
   :stage-effect :update,
   :state-effect :update,
   :term-status "testing"},
  :transfer
  {:accountable-effect :updateTo,
   :accounting-effect :decrementIncrement,
   :comment
   "Give full rights and responsibilities plus physical custody.",
   :contained-effect :notApplicable,
   :create-resource :optionalTo,
   :event-quantity :resource,
   :input-output :notApplicable,
   :label "transfer",
   :location-effect :updateTo,
   :onhand-effect :decrementIncrement,
   :pairs-with :notApplicable,
   :stage-effect :notApplicable,
   :state-effect :updateTo,
   :term-status "stable"},
  :transferAllRights
  {:accountable-effect :updateTo,
   :accounting-effect :decrementIncrement,
   :comment
   "Give full (in the human realm) rights and responsibilities to another agent, without transferring physical custody.",
   :contained-effect :notApplicable,
   :create-resource :optionalTo,
   :event-quantity :resource,
   :input-output :notApplicable,
   :label "transfer all rights",
   :location-effect :notApplicable,
   :onhand-effect :notApplicable,
   :pairs-with :notApplicable,
   :stage-effect :notApplicable,
   :state-effect :updateTo,
   :term-status "testing"},
  :transferCustody
  {:accountable-effect :notApplicable,
   :accounting-effect :notApplicable,
   :comment
   "Give physical custody and control of a resource, without full accounting or ownership rights.",
   :contained-effect :notApplicable,
   :create-resource :optionalTo,
   :event-quantity :resource,
   :input-output :notApplicable,
   :label "transfer custody",
   :location-effect :updateTo,
   :onhand-effect :decrementIncrement,
   :pairs-with :notApplicable,
   :stage-effect :notApplicable,
   :state-effect :updateTo,
   :term-status "testing"},
  :use
  {:accountable-effect :notApplicable,
   :accounting-effect :notApplicable,
   :comment
   "For example a tool used in process; after the process, the tool still exists.",
   :contained-effect :notApplicable,
   :create-resource :notApplicable,
   :event-quantity :both,
   :input-output :input,
   :label "use",
   :location-effect :notApplicable,
   :onhand-effect :notApplicable,
   :pairs-with :notApplicable,
   :stage-effect :notApplicable,
   :state-effect :update,
   :term-status "stable"},
  :work
  {:accountable-effect :notApplicable,
   :accounting-effect :notApplicable,
   :comment "Labor applied to a process.",
   :contained-effect :notApplicable,
   :create-resource :notApplicable,
   :event-quantity :effort,
   :input-output :input,
   :label "work",
   :location-effect :notApplicable,
   :onhand-effect :notApplicable,
   :pairs-with :notApplicable,
   :stage-effect :notApplicable,
   :state-effect :notApplicable,
   :term-status "stable"}},
 :classes
 {:AccountableEffect
  {:comment
   "The action has this effect on an inventoried resource primary accountable agent.",
   :label "Accountable Effect",
   :layer :knowledge,
   :term-status "testing"},
  :AccountingEffect
  {:comment
   "The action has this effect on an inventoried resource accounting quantity.",
   :label "Accounting Effect",
   :layer :knowledge,
   :term-status "testing"},
  :Action
  {:comment
   "An action verb defining the kind of flow and its behavior.",
   :label "Action",
   :term-status "stable"},
  :ActionDomain {:label "Domain for vf:action"},
  :Agent
  {:comment
   "An identifiable entity that can commit to and/or perform economic and/or ecological activity under its own power or authority.",
   :label "Agent",
   :term-status "stable"},
  :Agreement
  {:comment
   "A set of reciprocal commitments among economic agents, and/or a set of reciprocal economic events.",
   :label "Agreement",
   :term-status "stable"},
  :AgreementBundle
  {:comment
   "A grouping of agreements to bundle detailed line item reciprocity.",
   :label "Agreement Bundle",
   :term-status "testing"},
  :BatchLotRecord
  {:comment
   "A document which contains all the needed detail related to the production process of a particular batch or lot, a resource processed in the same process(es) so that it is expected to be homogeneous.",
   :label "Batch Lot Record",
   :term-status "testing"},
  :Claim
  {:comment
   "A claim for a future economic event(s) in reciprocity for an economic event that already occurred.",
   :label "Claim",
   :term-status "testing"},
  :ClassifiedAsDomain {:label "Domain for vf:classifiedAs"},
  :Commitment
  {:comment
   "A planned economic flow that has been scheduled or promised by one agent to another agent.",
   :label "Commitment",
   :term-status "stable"},
  :ContainedEffect
  {:comment
   "The action has this effect on an inventoried resource contained in resource.",
   :label "Contained Effect",
   :layer :knowledge,
   :term-status "testing"},
  :CreateResource
  {:comment "The action can create an economic resource.",
   :label "Create Resource",
   :layer :knowledge,
   :term-status "testing"},
  :CreatedDomain {:label "Domain for vf:created"},
  :DueDomain {:label "Domain for vf:due"},
  :EcologicalAgent
  {:comment
   "A non-human being; or a functional group of non-human beings; or an ecosystem of living beings that includes non-humans; but it has agency and receives and/or provides economic/ecological resources.",
   :label "Ecological Agent",
   :term-status "testing"},
  :EconomicEvent
  {:comment
   "An observed economic flow, which could reflect creation or a change in the quantity, location, accountability and/or responsibility, of an economic resource, whether material or not.",
   :label "Economic Event",
   :term-status "stable"},
  :EconomicResource
  {:comment
   "Economic or environmental things (material or digital), media of exchange, which agents agree should be accounted for and which can be inventoried.",
   :label "Economic Resource",
   :term-status "stable"},
  :EffortQuantityDomain {:label "Domain for vf:effortQuantity"},
  :EventQuantity
  {:comment
   "The action involves the event resource quantity, event quantity, or both.",
   :label "Event Quantity",
   :layer :knowledge,
   :term-status "testing"},
  :FinishedDomain {:label "Domain for vf:finished"},
  :HasBeginningDomain {:label "Domain for vf:hasBeginning"},
  :HasEndDomain {:label "Domain for vf:hasEnd"},
  :HasInputRange {:label "Range for vf:hasInput"},
  :HasOutputRange {:label "Range for vf:hasOutput"},
  :HasPointInTimeDomain {:label "Domain for vf:hasPointInTime"},
  :ImageDomain {:label "Domain for vf:image"},
  :ImageListDomain {:label "Domain for vf:imageList"},
  :InputOfDomain {:label "Domain for vf:inputOf"},
  :InputOutput
  {:comment
   "The action is an input or output of a process, or not applicable to a process.",
   :label "Input/Output",
   :layer :knowledge,
   :term-status "testing"},
  :Intent
  {:comment
   "A desired or proposed or planned or estimated economic flow, usually with only one agent associated, which could become a commitment and/or economic event.",
   :label "Intent",
   :term-status "stable"},
  :LabelDomain {:label "Domain for vf:label"},
  :LocationEffect
  {:comment
   "The action has this effect on an inventoried resource current location.",
   :label "Location Effect",
   :layer :knowledge,
   :term-status "testing"},
  :Measure
  {:comment
   "A quantity expressed as a numeric value with a unit of measure.",
   :label "Measure",
   :term-status "stable"},
  :NameDomain {:label "Domain for vf:name"},
  :NoteDomain {:label "Domain for vf:note"},
  :OnhandEffect
  {:comment
   "The action has this effect on an inventoried resource onhand quantity.",
   :label "Onhand Effect",
   :layer :knowledge,
   :term-status "testing"},
  :Organization
  {:comment
   "A functional structure, formal or informal, which can include people and/or other organizations, and has its own agency.  Something called a group is an Organization in Valueflows if it has agency as the group.",
   :label "Organization",
   :term-status "stable"},
  :OutputOfDomain {:label "Domain for vf:outputOf"},
  :Person
  {:comment "A human being. All persons are considered agents.",
   :label "Person",
   :term-status "stable"},
  :Plan
  {:comment
   "A logical collection of processes, with optional connected agreements, that constitute a body of scheduled work with defined deliverable(s).",
   :label "Plan",
   :term-status "stable"},
  :PlanIncludesRange {:label "Range for vf:planIncludes"},
  :PlannedWithinDomain {:label "Domain for vf:plannedWithin"},
  :Process
  {:comment
   "An activity that changes inputs into outputs, by transforming or transporting economic resource(s).",
   :label "Process",
   :term-status "stable"},
  :ProcessSpecification
  {:comment "Specifies the kind of process.",
   :label "Process Specification",
   :term-status "stable"},
  :Proposal
  {:comment
   "Published requests or offers, sometimes with what is expected in return.",
   :label "Proposal",
   :term-status "stable"},
  :ProposalList
  {:comment "A grouping of proposals, for publishing as a list.",
   :label "Proposal List",
   :term-status "testing"},
  :ProposalPurpose
  {:comment
   "The type of proposal: offer or request (other types may be added).",
   :label "Proposal Purpose",
   :term-status "testing"},
  :ProposedToDomain {:label "Domain for vf:proposedTo"},
  :ProviderDomain {:label "Domain for vf:provider"},
  :ReceiverDomain {:label "Domain for vf:receiver"},
  :Recipe
  {:comment
   "Optional instance of a recipe which directly specifies the recipe processes included.",
   :label "Recipe",
   :term-status "testing"},
  :RecipeExchange
  {:comment
   "Specifies an exchange type agreement as part of a recipe.",
   :label "Recipe Exchange",
   :term-status "stable"},
  :RecipeFlow
  {:comment
   "The specification of a resource inflow to, or outflow from, a recipe process; and/or a clause, or reciprocal clause, of a recipe exchange.",
   :label "Recipe Flow",
   :term-status "stable"},
  :RecipeProcess
  {:comment
   "Specifies a process in a recipe for use in planning from recipe.",
   :label "Recipe Process",
   :term-status "stable"},
  :ResourceClassifiedAsDomain
  {:label "Domain for vf:resourceClassifiedAs"},
  :ResourceConformsToDomain
  {:label "Domain for vf:resourceConformsTo"},
  :ResourceInventoriedAsDomain
  {:label "Domain for vf:resourceInventoriedAs"},
  :ResourceQuantityDomain {:label "Domain for vf:resourceQuantity"},
  :ResourceSpecification
  {:comment
   "Specifies the kind of economic or environmental resource, even if the resource is not instantiated as an EconomicResource. Could define a material or digital thing, service, medium of exchange or currency, skill or type of work.",
   :label "Resource Specification",
   :term-status "stable"},
  :SatisfiesDomain {:label "Domain for vf:satisfies"},
  :SpatialThing
  {:comment
   "Data that locates something relative to the Earth, usually a somewhat fixed location.",
   :label "Spatial Thing",
   :term-status "stable"},
  :StageDomain {:label "Domain for vf:stage"},
  :StageEffect
  {:comment
   "The action has this effect on an inventoried resource stage.",
   :label "Stage Effect",
   :layer :knowledge,
   :term-status "testing"},
  :StateDomain {:label "Domain for vf:state"},
  :StateEffect
  {:comment
   "The action has this effect on an inventoried resource state.",
   :label "State Effect",
   :layer :knowledge,
   :term-status "unstable"},
  :Unit
  {:comment
   "A standard unit of measure, defined and adopted by convention or by law.",
   :label "Unit",
   :term-status "stable"}},
 :counts {:actions 19, :classes 67, :individuals 19, :properties 111},
 :enums
 {:AccountableEffect #{:new :updateTo},
  :AccountingEffect
  #{:decrement :decrementIncrement :increment :incrementTo},
  :ContainedEffect #{:notApplicable :remove :update :updateTo},
  :CreateResource #{:notApplicable :optional :optionalTo},
  :EventQuantity #{:both :effort :resource},
  :InputOutput #{:input :notApplicable :output :outputInput},
  :LocationEffect #{:new :notApplicable :update :updateTo},
  :OnhandEffect
  #{:decrement :decrementIncrement :increment :incrementTo},
  :PairsWith #{:notApplicable},
  :ProposalPurpose #{:offer :request},
  :StageEffect #{:update},
  :StateEffect #{:update :updateTo}},
 :generated-by "bin/ingest.cljs — DO NOT EDIT BY HAND",
 :individuals
 {:both
  {:comment "This event can use resourceQuantity and effortQuantity.",
   :label "both",
   :member-of #{:EventQuantity},
   :term-status "testing"},
  :decrement
  {:comment
   "The effect is to subtract from the inventoried resource accounting and/or onhand quantity.",
   :label "decrement",
   :member-of #{:AccountingEffect :OnhandEffect},
   :term-status "stable"},
  :decrementIncrement
  {:comment
   "The effect is to subtract from the 'from' inventoried resource, and add to the 'to' inventoried resource, accounting and/or onhand quantity.",
   :label "decrement/increment",
   :member-of #{:AccountingEffect :OnhandEffect},
   :term-status "stable"},
  :effort
  {:comment "This event uses effortQuantity.",
   :label "effort",
   :member-of #{:EventQuantity},
   :term-status "testing"},
  :increment
  {:comment
   "The effect is to add to the inventoried resource accounting and/or onhand quantity.",
   :label "increment",
   :member-of #{:AccountingEffect :OnhandEffect},
   :term-status "stable"},
  :incrementTo
  {:comment
   "The effect is to add to the to (receiver) inventoried resource accounting and/or onhand quantity.",
   :label "increment to",
   :member-of #{:AccountingEffect :OnhandEffect},
   :term-status "stable"},
  :input
  {:comment "This kind of flow can be an input to a process.",
   :label "input",
   :member-of #{:InputOutput},
   :term-status "stable"},
  :new
  {:comment
   "The effect applies for a new resource created by the event.",
   :label "new",
   :member-of #{:AccountableEffect :LocationEffect},
   :term-status "testing"},
  :notApplicable
  {:comment "This property is not applicable to this kind of flow.",
   :label "not applicable",
   :member-of
   #{:ContainedEffect :CreateResource :InputOutput :LocationEffect
     :PairsWith},
   :term-status "testing"},
  :offer
  {:comment "The proposal is an offer.",
   :label "offer",
   :member-of #{:ProposalPurpose},
   :term-status "testing"},
  :optional
  {:comment
   "This kind of flow gives the user the option to create a new resource using resourceInventoriedAs.",
   :label "optional",
   :member-of #{:CreateResource},
   :term-status "testing"},
  :optionalTo
  {:comment
   "This kind of flow gives the user the option to create a new resource using toResourceInventoriedAs.",
   :label "optional to",
   :member-of #{:CreateResource},
   :term-status "testing"},
  :output
  {:comment "This kind of flow can be an output from a process.",
   :label "output",
   :member-of #{:InputOutput},
   :term-status "stable"},
  :outputInput
  {:comment
   "This kind of flow can be an output from a process, and at the same time an input to another process.",
   :label "output input",
   :member-of #{:InputOutput},
   :term-status "testing"},
  :remove
  {:comment
   "The effect is to remove or nullify the specified property from the resource.",
   :label "remove",
   :member-of #{:ContainedEffect},
   :term-status "testing"},
  :request
  {:comment "The proposal is a published request, need, want.",
   :label "request",
   :member-of #{:ProposalPurpose},
   :term-status "testing"},
  :resource
  {:comment "This event uses resourceQuantity.",
   :label "resource",
   :member-of #{:EventQuantity},
   :term-status "testing"},
  :update
  {:comment
   "The effect is to update the resource in the specified property.",
   :label "update",
   :member-of
   #{:ContainedEffect :LocationEffect :StageEffect :StateEffect},
   :term-status "testing"},
  :updateTo
  {:comment
   "The effect is to update the to resource in the specified property.",
   :label "update",
   :member-of
   #{:AccountableEffect :ContainedEffect :LocationEffect :StateEffect},
   :term-status "testing"}},
 :properties
 {:accountableEffect
  {:comment
   "The primaryAccountable should be updated to the event receiver, or not.",
   :domain :Action,
   :kind :object,
   :label "accountable effect",
   :range :AccountableEffect,
   :term-status "testing"},
  :accountingEffect
  {:comment
   "The increment and/or decrement effect the action will have on the accounting quantity of an inventoried resource.",
   :domain :Action,
   :kind :object,
   :label "accounting effect",
   :range :AccountingEffect,
   :term-status "testing"},
  :accountingQuantity
  {:comment
   "The current amount and unit of the economic resource for which the agent has primary rights and responsibilities, sometimes thought of as ownership. This can be either stored or derived from economic events affecting the resource.",
   :domain :EconomicResource,
   :kind :object,
   :label "accounting quantity",
   :range :Measure,
   :term-status "stable"},
  :action
  {:comment
   "Defines the kind of flow, such as consume, produce, work, transfer, etc.",
   :domain :ActionDomain,
   :kind :object,
   :label "action",
   :range :Action,
   :term-status "stable"},
  :alt
  {:comment
   "The WGS84 altitude of a spatial thing (decimal meters above the local reference ellipsoid)",
   :domain :SpatialThing,
   :kind :datatype,
   :label "altitude",
   :range :dtype/numericUnion,
   :term-status "stable"},
  :availableQuantity
  {:comment
   "The amount and unit of the offered resource currently available.",
   :domain :Intent,
   :kind :object,
   :label "available quantity",
   :range :Measure,
   :term-status "stable"},
  :basedOn
  {:comment "The definition or standard specification for a process.",
   :domain :Process,
   :kind :object,
   :label "based on",
   :range :ProcessSpecification,
   :term-status "stable"},
  :batchLotCode
  {:comment
   "The code or identifier for this batch or lot, used to physically label individuals in the batch or lot.",
   :domain :BatchLotRecord,
   :kind :datatype,
   :label "batch or lot code",
   :range :xsd/string,
   :term-status "testing"},
  :bundledIn
  {:comment
   "This agreement is bundled with other agreements, for example in an order.",
   :domain :Agreement,
   :kind :object,
   :label "bundled in",
   :range :AgreementBundle,
   :term-status "testing"},
  :bundles
  {:comment "All the agreements included in this agreement bundle.",
   :domain :AgreementBundle,
   :kind :object,
   :label "bundles",
   :range :Agreement,
   :term-status "testing"},
  :classifiedAs
  {:comment
   "References one or more uri's for a concept in a common taxonomy or other classification scheme for purposes of categorization or grouping; or it can be one or more string classifications such as tags.",
   :domain :ClassifiedAsDomain,
   :kind :object,
   :label "classified as",
   :range :xsd/string,
   :term-status "testing"},
  :clauseOf
  {:comment "This commitment is a primary part of the agreement.",
   :domain :Commitment,
   :kind :object,
   :label "clause of",
   :range :Agreement,
   :term-status "stable"},
  :conformsTo
  {:comment
   "The primary resource specification or definition of an economic resource.",
   :domain :EconomicResource,
   :kind :object,
   :label "conforms to",
   :range :ResourceSpecification,
   :term-status "stable"},
  :containedEffect
  {:comment "The contained in resource should be updated or removed.",
   :domain :Action,
   :kind :object,
   :label "contained effect",
   :range :ContainedEffect,
   :term-status "testing"},
  :containedIn
  {:comment
   "Used when an economic resource contains units also defined as separate economic resources, for example a tool kit or a package of resources for shipping.",
   :domain :EconomicResource,
   :kind :object,
   :label "contained in",
   :range :EconomicResource,
   :term-status "testing"},
  :contains
  {:comment
   "An economic resource contains at least one other economic resource, for example a tool kit or package of resources for shipping.",
   :domain :EconomicResource,
   :kind :object,
   :label "contains",
   :range :EconomicResource,
   :term-status "testing"},
  :corrects
  {:comment
   "Used when an event was entered incorrectly and needs to be backed out or corrected. (The initial event cannot be changed.)",
   :domain :EconomicEvent,
   :kind :object,
   :label "corrects",
   :range :EconomicEvent,
   :term-status "testing"},
  :createResource
  {:comment "The action can create an economic resource.",
   :domain :Action,
   :kind :object,
   :label "can create resource",
   :range :CreateResource,
   :term-status "testing"},
  :created
  {:comment
   "The date, and time if desired, the information was agreed to or recorded.",
   :domain :CreatedDomain,
   :kind :datatype,
   :label "created",
   :range :xsd/dateTimeStamp,
   :term-status "stable"},
  :currentCurrencyLocation
  {:comment
   "The current virtual place a currency economic resource is located, for example the address for a bank account, crypto wallet, etc., in a domain standard format.",
   :domain :EconomicResource,
   :kind :datatype,
   :label "current currency location",
   :range :xsd/string,
   :term-status "testing"},
  :currentLocation
  {:comment
   "The current physical location of an economic resource.  Could be at any level of granularity, from a town to an address to a warehouse location.  Usually mappable.",
   :domain :EconomicResource,
   :kind :object,
   :label "current location",
   :range :SpatialThing,
   :term-status "stable"},
  :currentVirtualLocation
  {:comment
   "The current virtual place a digital economic resource is located. Usually used for documents, code, or other electronic resource.",
   :domain :EconomicResource,
   :kind :datatype,
   :label "current virtual location",
   :range :xsd/anyURI,
   :term-status "stable"},
  :defaultUnitOfEffort
  {:comment
   "The default unit used for use or work or sometimes cite actions.",
   :domain :ResourceSpecification,
   :kind :object,
   :label "default unit of effort",
   :range :Unit,
   :term-status "stable"},
  :defaultUnitOfResource
  {:comment "The default unit used for the resource itself.",
   :domain :ResourceSpecification,
   :kind :object,
   :label "default unit of resource",
   :range :Unit,
   :term-status "stable"},
  :due
  {:comment
   "The date, and time if desired, something is expected to be complete.",
   :domain :DueDomain,
   :kind :datatype,
   :label "due",
   :range :xsd/dateTimeStamp,
   :term-status "stable"},
  :effortQuantity
  {:comment
   "The amount and unit of the work or use or citation effort-based action. This is often expressed with a time unit, but also could be cycle counts or other measures of effort or usefulness.",
   :domain :EffortQuantityDomain,
   :kind :object,
   :label "effort quantity",
   :range :Measure,
   :term-status "stable"},
  :eligibleLocation
  {:comment "Location or area where the proposal is valid.",
   :domain :Proposal,
   :kind :object,
   :label "eligible location",
   :range :SpatialThing,
   :term-status "testing"},
  :eventQuantity
  {:comment
   "The event quantity applicable is resource quantity, effort quantity, or both.",
   :domain :Action,
   :kind :object,
   :label "event quantity",
   :range :EventQuantity,
   :term-status "testing"},
  :expirationDate
  {:comment
   "The date after which a resource of this batch or lot should no longer be used or consumed.",
   :domain :BatchLotRecord,
   :kind :datatype,
   :label "expiration date",
   :range :xsd/dateTimeStamp,
   :term-status "testing"},
  :finished
  {:comment
   "The flow or process is complete or not.  This is irrespective of if the original goal has been met, and indicates simply that no more will be done.  Default false.",
   :domain :FinishedDomain,
   :kind :datatype,
   :label "finished",
   :range :xsd/boolean,
   :term-status "stable"},
  :fulfills
  {:comment
   "The commitment(s) fulfilled completely or partially by an economic event.",
   :domain :EconomicEvent,
   :kind :object,
   :label "fulfills",
   :range :Commitment,
   :term-status "stable"},
  :hasBeginning
  {:comment
   "The planned or actual beginning date, and time if desired, of a flow or process.",
   :domain :HasBeginningDomain,
   :kind :datatype,
   :label "has beginning",
   :range :xsd/dateTimeStamp,
   :term-status "stable"},
  :hasDetailedGeometry
  {:comment
   "A spatial geometry of any complexity and tooling supported by geosparql.",
   :domain :SpatialThing,
   :kind :object,
   :label "has detailed geometry",
   :range :geosparql/Geometry,
   :term-status "testing"},
  :hasDuration
  {:comment "The temporal extent of the process.",
   :domain :RecipeProcess,
   :kind :object,
   :label "has duration",
   :range :Measure,
   :term-status "stable"},
  :hasEnd
  {:comment
   "The planned or actual ending date, and time if desired, of a flow or process.",
   :domain :HasEndDomain,
   :kind :datatype,
   :label "has end",
   :range :xsd/dateTimeStamp,
   :term-status "stable"},
  :hasIndependentDemand
  {:comment
   "The commitments and/or intents which this plan was created to deliver on.",
   :domain :Plan,
   :kind :object,
   :label "has independent demand",
   :range :Commitment,
   :term-status "stable"},
  :hasInput
  {:comment "All the input flows of a process.",
   :domain :Process,
   :kind :object,
   :label "has input",
   :range :HasInputRange,
   :term-status "stable"},
  :hasNumericalValue
  {:comment "A numeric amount.",
   :domain :Measure,
   :kind :datatype,
   :label "has numerical value",
   :range :dtype/numericUnion,
   :term-status "stable"},
  :hasOutput
  {:comment "All the output flows of a process.",
   :domain :Process,
   :kind :object,
   :label "has output",
   :range :HasOutputRange,
   :term-status "stable"},
  :hasPointInTime
  {:comment
   "The planned or actual date, and time if desired, of a flow; can be used instead of hasBeginning and hasEnd, if so, hasBeginning and hasEnd should be able to return this value.",
   :domain :HasPointInTimeDomain,
   :kind :datatype,
   :label "has point in time",
   :range :xsd/dateTimeStamp,
   :term-status "stable"},
  :hasRecipeInput
  {:comment "All the inputs of a recipe process.",
   :domain :RecipeProcess,
   :kind :object,
   :label "has recipe input",
   :range :RecipeFlow,
   :term-status "stable"},
  :hasRecipeOutput
  {:comment "All the outputs of a recipe process.",
   :domain :RecipeProcess,
   :kind :object,
   :label "has recipe output",
   :range :RecipeFlow,
   :term-status "stable"},
  :hasUnit
  {:comment "A standard unit of measure.",
   :domain :Measure,
   :kind :object,
   :label "has unit",
   :range :Unit,
   :term-status "stable"},
  :image
  {:comment
   "The uri to an image relevant to the entity, such as a logo, avatar, photo, diagram, etc.",
   :domain :ImageDomain,
   :kind :datatype,
   :label "image",
   :range :xsd/anyURI,
   :term-status "stable"},
  :imageList
  {:comment
   "A comma separated list of uri addresses to images relevant to the resource.",
   :domain :ImageListDomain,
   :kind :datatype,
   :label "image list",
   :range :xsd/anyURI,
   :term-status "stable"},
  :inScopeOf
  {:comment "Scope here means executed in the context of an agent.",
   :domain :Process,
   :kind :object,
   :label "in scope of",
   :range :Agent,
   :term-status "testing"},
  :independentDemandOf
  {:comment
   "This plan is the way this commitment or intent will be realized.",
   :domain :Commitment,
   :kind :object,
   :label "independent demand of",
   :range :Plan,
   :term-status "stable"},
  :inputOf
  {:comment "Relates an input flow to its process.",
   :domain :InputOfDomain,
   :kind :object,
   :label "input of",
   :range :Process,
   :term-status "stable"},
  :inputOutput
  {:comment
   "Denotes if a process input or output, or not applicable to a process.",
   :domain :Action,
   :kind :object,
   :label "input/output",
   :range :InputOutput,
   :term-status "testing"},
  :label
  {:comment "The label defined for human readable display.",
   :domain :LabelDomain,
   :kind :datatype,
   :label "label",
   :range :xsd/string,
   :term-status "stable"},
  :lat
  {:comment "The WGS84 latitude of a spatial thing (decimal degrees).",
   :domain :SpatialThing,
   :kind :datatype,
   :label "latitude",
   :range :dtype/numericUnion,
   :term-status "stable"},
  :listedIn
  {:comment "This proposal is part of these lists of proposals.",
   :domain :Proposal,
   :kind :object,
   :label "listed in",
   :range :ProposalList,
   :term-status "testing"},
  :lists
  {:comment "All the proposals included in this proposal list.",
   :domain :ProposalList,
   :kind :object,
   :label "lists",
   :range :Proposal,
   :term-status "testing"},
  :locationEffect
  {:comment
   "This action can update the current location of an inventoried resource.",
   :domain :Action,
   :kind :object,
   :label "location effect",
   :range :LocationEffect,
   :term-status "testing"},
  :long
  {:comment
   "The WGS84 longitude of a spatial thing (decimal degrees).",
   :domain :SpatialThing,
   :kind :datatype,
   :label "longitude",
   :range :dtype/numericUnion,
   :term-status "stable"},
  :mappableAddress
  {:comment
   "A textual address that can be mapped using mapping software.",
   :domain :SpatialThing,
   :kind :datatype,
   :label "mappable address",
   :range :xsd/string,
   :term-status "stable"},
  :mediumOfExchange
  {:comment
   "True if the resource is a currency, money, token, credit, etc. used as a medium of exchange.  Default false.",
   :domain :ResourceSpecification,
   :kind :datatype,
   :label "medium of exchange",
   :range :xsd/boolean,
   :term-status "testing"},
  :minimumQuantity
  {:comment
   "The minimum required order amount and unit of the offered resource.",
   :domain :Intent,
   :kind :object,
   :label "minimum quantity",
   :range :Measure,
   :term-status "stable"},
  :name
  {:comment
   "An informal or formal textual identifier for an object. Does not imply uniqueness.",
   :domain :NameDomain,
   :kind :datatype,
   :label "name",
   :range :xsd/string,
   :term-status "stable"},
  :note
  {:comment "Any useful textual information related to the item.",
   :domain :NoteDomain,
   :kind :datatype,
   :label "note",
   :range :xsd/string,
   :term-status "stable"},
  :ofBatchLot
  {:comment
   "The batch lot record of this resource, if it is a batch or lot resource.",
   :domain :EconomicResource,
   :kind :object,
   :label "of batch or lot",
   :range :BatchLotRecord,
   :term-status "testing"},
  :omUnitIdentifier
  {:comment
   "The unique identifier of the om unit of measure, for standardization across networks.",
   :domain :Unit,
   :kind :datatype,
   :label "om unit identifier",
   :range :xsd/anyURI,
   :term-status "stable"},
  :onhandEffect
  {:comment
   "The increment and/or decrement effect the action will have on the onhand quantity of an inventoried resource.",
   :domain :Action,
   :kind :object,
   :label "onhand effect",
   :range :OnhandEffect,
   :term-status "testing"},
  :onhandQuantity
  {:comment
   "The current amount and unit of the economic resource which is under direct control of the agent.  It may be more or less than the accounting quantity. This can be either stored or derived from economic events affecting the resource.",
   :domain :EconomicResource,
   :kind :object,
   :label "onhand quantity",
   :range :Measure,
   :term-status "stable"},
  :outputOf
  {:comment "Relates an output flow to its process.",
   :domain :OutputOfDomain,
   :kind :object,
   :label "output of",
   :range :Process,
   :term-status "stable"},
  :pairsWith
  {:comment
   "The action that usually affects the same resource as a complement in the same flow.",
   :domain :Action,
   :kind :object,
   :label "pairs with",
   :range :Action,
   :term-status "testing"},
  :planIncludes
  {:comment
   "The processes and non-process commitments/intents that constitute the plan.",
   :domain :Plan,
   :kind :object,
   :label "plan includes",
   :range :PlanIncludesRange,
   :term-status "stable"},
  :plannedWithin
  {:comment
   "The process with its inputs and outputs, or the non-process commitment or intent, is part of the plan.",
   :domain :PlannedWithinDomain,
   :kind :object,
   :label "planned within",
   :range :Plan,
   :term-status "stable"},
  :primaryAccountable
  {:comment
   "The agent currently with primary rights and responsibilites for the economic resource. It is the agent that is associated with the accountingQuantity of the economic resource.",
   :domain :EconomicResource,
   :kind :object,
   :label "primary accountable",
   :range :Agent,
   :term-status "stable"},
  :primaryLocation
  {:comment
   "The main place an agent is located, often an address where activities occur and mail can be sent. This is usually a mappable geographic location.",
   :domain :Agent,
   :kind :object,
   :label "primary location",
   :range :SpatialThing,
   :term-status "stable"},
  :primaryOutput
  {:comment
   "The main type of resource the recipe is intended to produce or deliver.",
   :domain :Recipe,
   :kind :object,
   :label "primary output",
   :range :ResourceSpecification,
   :term-status "testing"},
  :processClassifiedAs
  {:comment
   "References one or more uri's for a concept in a common taxonomy or other classification scheme for purposes of categorization or grouping; or can be one or more string classifications such as tags.",
   :domain :RecipeProcess,
   :kind :object,
   :label "process classified as",
   :range :xsd/string,
   :term-status "testing"},
  :processConformsTo
  {:comment
   "The standard specification or definition of a type of process.",
   :domain :RecipeProcess,
   :kind :object,
   :label "process conforms to",
   :range :ProcessSpecification,
   :term-status "stable"},
  :proposedTo
  {:comment
   "The agent(s) to which the proposal or proposal list is published.",
   :domain :ProposedToDomain,
   :kind :object,
   :label "proposed to",
   :range :Agent,
   :term-status "testing"},
  :provider
  {:comment
   "The economic agent by whom the intended, committed, or actual economic event is initiated.",
   :domain :ProviderDomain,
   :kind :object,
   :label "provider",
   :range :Agent,
   :term-status "stable"},
  :publishes
  {:comment
   "The primary intent(s) of this published proposal. Would be used in intent matching.",
   :domain :Proposal,
   :kind :object,
   :label "publishes",
   :range :Intent,
   :term-status "stable"},
  :purpose
  {:comment
   "The type of proposal, whether offer or request (others may be added as need arises).",
   :domain :Proposal,
   :kind :object,
   :label "purpose",
   :range :ProposalPurpose,
   :term-status "testing"},
  :realizationOf
  {:comment
   "This non-reciprocal economic event occurs as part of this agreement.",
   :domain :EconomicEvent,
   :kind :object,
   :label "realization of",
   :range :Agreement,
   :term-status "stable"},
  :realizes
  {:comment
   "All the non-reciprocal economic events (with or without commitments) that realize the agreement.",
   :domain :Agreement,
   :kind :object,
   :label "realizes",
   :range :EconomicEvent,
   :term-status "stable"},
  :realizesReciprocal
  {:comment
   "All the reciprocal economic events (with or without commitments) that realize the agreement.",
   :domain :Agreement,
   :kind :object,
   :label "realizes reciprocal",
   :range :EconomicEvent,
   :term-status "stable"},
  :receiver
  {:comment
   "The economic agent whom the intended, committed, or actual economic event is for.",
   :domain :ReceiverDomain,
   :kind :object,
   :label "receiver",
   :range :Agent,
   :term-status "stable"},
  :recipeClauseOf
  {:comment "Relates a flow to its exchange agreement in a recipe.",
   :domain :RecipeFlow,
   :kind :object,
   :label "recipe clause of",
   :range :RecipeExchange,
   :term-status "stable"},
  :recipeIncludes
  {:comment "The collection of processes needed for this recipe.",
   :domain :Recipe,
   :kind :object,
   :label "recipe includes",
   :range :RecipeProcess,
   :term-status "testing"},
  :recipeInputOf
  {:comment "Relates an input flow to its process in a recipe.",
   :domain :RecipeFlow,
   :kind :object,
   :label "recipe input of",
   :range :RecipeProcess,
   :term-status "stable"},
  :recipeOutputOf
  {:comment "Relates an output flow to its process in a recipe.",
   :domain :RecipeFlow,
   :kind :object,
   :label "recipe output of",
   :range :RecipeProcess,
   :term-status "stable"},
  :recipeReciprocalClauseOf
  {:comment
   "Relates a reciprocal flow to its exchange agreement in a recipe.",
   :domain :RecipeFlow,
   :kind :object,
   :label "recipe reciprocal clause of",
   :range :RecipeExchange,
   :term-status "stable"},
  :recipeStipulates
  {:comment "All the primary clauses of a recipe exchange.",
   :domain :RecipeExchange,
   :kind :object,
   :label "recipe stipulates",
   :range :RecipeFlow,
   :term-status "stable"},
  :recipeStipulatesReciprocal
  {:comment "All the reciprocal clauses of a recipe exchange.",
   :domain :RecipeExchange,
   :kind :object,
   :label "recipe stipulates reciprocal",
   :range :RecipeFlow,
   :term-status "stable"},
  :reciprocal
  {:comment
   "The reciprocal intent(s) of this published proposal. Not meant to be used for intent matching.",
   :domain :Proposal,
   :kind :object,
   :label "reciprocal",
   :range :Intent,
   :term-status "stable"},
  :reciprocalClauseOf
  {:comment "This commitment is a reciprocal part of the agreement.",
   :domain :Commitment,
   :kind :object,
   :label "reciprocal clause of",
   :range :Agreement,
   :term-status "stable"},
  :reciprocalRealizationOf
  {:comment
   "This reciprocal economic event occurs as part of this agreement.",
   :domain :EconomicEvent,
   :kind :object,
   :label "reciprocal realization of",
   :range :Agreement,
   :term-status "stable"},
  :resourceClassifiedAs
  {:comment
   "References one or more uri's for a concept in a common taxonomy or other classification scheme for purposes of categorization or grouping; or can be one or more string classifications such as tags.",
   :domain :ResourceClassifiedAsDomain,
   :kind :object,
   :label "resource classified as",
   :range :xsd/string,
   :term-status "testing"},
  :resourceConformsTo
  {:comment
   "The lowest level resource specification or definition of an existing or potential economic resource, whether one will ever be instantiated or not.",
   :domain :ResourceConformsToDomain,
   :kind :object,
   :label "resource conforms to",
   :range :ResourceSpecification,
   :term-status "stable"},
  :resourceInventoriedAs
  {:comment "Economic resource involved in the flow.",
   :domain :ResourceInventoriedAsDomain,
   :kind :object,
   :label "resource inventoried as",
   :range :EconomicResource,
   :term-status "stable"},
  :resourceQuantity
  {:comment
   "The amount and unit of the economic resource counted or inventoried.",
   :domain :ResourceQuantityDomain,
   :kind :object,
   :label "resource quantity",
   :range :Measure,
   :term-status "stable"},
  :satisfies
  {:comment
   "The intent(s) satisfied fully or partially by an economic event or commitment.",
   :domain :SatisfiesDomain,
   :kind :object,
   :label "satisfies",
   :range :Intent,
   :term-status "stable"},
  :settles
  {:comment
   "The claim(s) settled fully or partially by the economic event.",
   :domain :EconomicEvent,
   :kind :object,
   :label "settles",
   :range :Claim,
   :term-status "testing"},
  :stage
  {:comment
   "The required stage of the desired input economic resource. References the ProcessSpecification of the last process the economic resource went through.",
   :domain :StageDomain,
   :kind :object,
   :label "stage",
   :range :ProcessSpecification,
   :term-status "stable"},
  :stageEffect
  {:comment
   "The stage of the inventoried resource should be updated, or not.",
   :domain :Action,
   :kind :object,
   :label "stage effect",
   :range :StageEffect,
   :term-status "testing"},
  :state
  {:comment
   "The required state of the desired input economic resource, after coming out of a test or review process.",
   :domain :StateDomain,
   :kind :object,
   :label "state",
   :range :xsd/string,
   :term-status "testing"},
  :stateEffect
  {:comment
   "The state of the from or to inventoried resource should be updated, or not.",
   :domain :Action,
   :kind :object,
   :label "state effect",
   :range :StateEffect,
   :term-status "testing"},
  :stipulates
  {:comment
   "All the primary commitments that constitute the agreement.",
   :domain :Agreement,
   :kind :object,
   :label "stipulates",
   :range :Commitment,
   :term-status "stable"},
  :stipulatesReciprocal
  {:comment
   "All the reciprocal commitments that constitute the agreement.",
   :domain :Agreement,
   :kind :object,
   :label "stipulates reciprocal",
   :range :Commitment,
   :term-status "stable"},
  :substitutable
  {:comment
   "Defines if any resource of that type can be freely substituted for any other resource of that type when used, consumed, traded, etc.",
   :domain :ResourceSpecification,
   :kind :datatype,
   :label "substitutable",
   :range :xsd/boolean,
   :term-status "stable"},
  :symbol
  {:comment "The symbol defined for human readable display.",
   :domain :Unit,
   :kind :datatype,
   :label "symbol",
   :range :xsd/string,
   :term-status "stable"},
  :toLocation
  {:comment "The new location of the receiver resource.",
   :domain :EconomicEvent,
   :kind :object,
   :label "to location",
   :range :SpatialThing,
   :term-status "stable"},
  :toResourceInventoriedAs
  {:comment
   "Additional economic resource on the economic event when needed by the receiver. Used when a transfer or move, or sometimes other actions, requires explicitly identifying an economic resource by the receiver, which is identified differently by the sender.",
   :domain :EconomicEvent,
   :kind :object,
   :label "to resource inventoried as",
   :range :EconomicResource,
   :term-status "stable"},
  :trackingIdentifier
  {:comment
   "Any identifier used to track a singular resource, such as a serial number or VIN.",
   :domain :EconomicResource,
   :kind :datatype,
   :label "tracking identifier",
   :range :xsd/string,
   :term-status "stable"},
  :triggeredBy
  {:comment
   "References an economic event that implied the claim, often based on a prior agreement.",
   :domain :Claim,
   :kind :object,
   :label "triggered by",
   :range :EconomicEvent,
   :term-status "testing"},
  :unitBased
  {:comment
   "This group of intents contains unit based quantities, which can be multipied to create commitments; commonly seen in a price list or e-commerce. Default false.",
   :domain :Proposal,
   :kind :datatype,
   :label "unit based",
   :range :xsd/boolean,
   :term-status "stable"},
  :unitOfEffort
  {:comment "The unit used for use or work or sometimes cite actions.",
   :domain :EconomicResource,
   :kind :object,
   :label "unit of effort",
   :range :Unit,
   :term-status "stable"}},
 :schema "valueflows.vocabulary.v1",
 :upstream
 {:algorithms-doc "https://www.valueflo.ws/algorithms/overview/",
  :base "https://w3id.org/valueflows/ont/vf",
  :bytes 87877,
  :documentation "https://www.valueflo.ws/",
  :fetched-at "2026-08-15",
  :file "resources/valueflows/all_vf.ttl",
  :license
  "Creative Commons Attribution 4.0 (upstream declares cc:license)",
  :sha256
  "47cada8122561100520702e2998c2949f6f4f42ba550c36797791882cbc48ece",
  :source-url
  "https://codeberg.org/valueflows/pages/raw/branch/main/assets/all_vf.TTL"}}
)
