;; GENERATED by bin/units.cljs from resources/valueflows/units.edn.
;; DO NOT EDIT BY HAND. Regenerate: nbb bin/units.cljs
;;
;; Inlined so a portable `.cljc` needs no host I/O to read the registry.

(ns valueflows.unit-data)

(def registry
{:day
 {:aliases #{:days},
  :authority :om-2,
  :label "day",
  :om-2 "day",
  :quantity-kind :time,
  :symbol "d"},
 :each
 {:aliases #{:piece :pieces :pcs :ea :unit :units},
  :authority :om-2,
  :label "piece",
  :note
  "om-2 has no `each`. A count of things is `piece`; `one` is the\n                 dimensionless ratio, which is a different quantity kind.",
  :om-2 "piece",
  :quantity-kind :count,
  :symbol "ea"},
 :en
 {:aliases #{:EN},
  :authority :none,
  :label "EN",
  :note
  "ENGI mutual-credit unit (cloud-itonami/credits). Integer\n                 micro-EN in the ledger; net supply is zero by construction.\n                 Deliberately NOT :currency — it is not purchased, has no\n                 issuer, and pays no interest, so treating it as money would\n                 let it be added to yen.",
  :quantity-kind :mutual-credit,
  :symbol "EN"},
 :eur
 {:aliases #{:euro :EUR},
  :authority :om-2,
  :iso-4217 "EUR",
  :label "euro",
  :note
  "om-2 spells this one lowercase while it capitalises the others",
  :om-2 "euro",
  :quantity-kind :currency,
  :symbol "€"},
 :g
 {:aliases #{:gram :grams},
  :authority :om-2,
  :label "gram",
  :om-2 "gram",
  :quantity-kind :mass,
  :symbol "g"},
 :hour
 {:aliases #{:hours :hr :hrs :h},
  :authority :om-2,
  :label "hour",
  :om-2 "hour",
  :quantity-kind :time,
  :symbol "h"},
 :jpy
 {:aliases #{:yen :JPY},
  :authority :om-2,
  :iso-4217 "JPY",
  :label "Japanese yen",
  :om-2 "JapaneseYen",
  :quantity-kind :currency,
  :symbol "¥"},
 :kg
 {:aliases #{:kilogram :kilograms :kgs},
  :authority :om-2,
  :label "kilogram",
  :om-2 "kilogram",
  :quantity-kind :mass,
  :symbol "kg"},
 :litre
 {:aliases #{:liter :liters :litres :l},
  :authority :om-2,
  :label "litre",
  :om-2 "litre",
  :quantity-kind :volume,
  :symbol "L"},
 :metre
 {:aliases #{:meter :meters :metres :m},
  :authority :om-2,
  :label "metre",
  :om-2 "metre",
  :quantity-kind :length,
  :symbol "m"},
 :minute
 {:aliases #{:minutes :min},
  :authority :om-2,
  :label "minute",
  :note
  "om-2 name is minute-Time; a bare `minute` does not exist there",
  :om-2 "minute-Time",
  :quantity-kind :time,
  :symbol "min"},
 :percent
 {:aliases #{:pct},
  :authority :om-2,
  :label "percent",
  :om-2 "percent",
  :quantity-kind :ratio,
  :symbol "%"},
 :ratio
 {:aliases #{:one :dimensionless},
  :authority :om-2,
  :label "one",
  :om-2 "one",
  :quantity-kind :ratio,
  :symbol "1"},
 :second
 {:aliases #{:seconds :sec :s},
  :authority :om-2,
  :label "second",
  :note "om-2 name is second-Time, because second-Angle also exists",
  :om-2 "second-Time",
  :quantity-kind :time,
  :symbol "s"},
 :t
 {:aliases #{:tonne :tonnes :metric-ton},
  :authority :om-2,
  :label "tonne",
  :om-2 "tonne",
  :quantity-kind :mass,
  :symbol "t"},
 :usd
 {:aliases #{:dollar :USD},
  :authority :om-2,
  :iso-4217 "USD",
  :label "United States dollar",
  :om-2 "UnitedStatesDollar",
  :quantity-kind :currency,
  :symbol "$"},
 :week
 {:aliases #{:weeks},
  :authority :om-2,
  :label "week", 
  :om-2 "week", 
  :quantity-kind :time, 
  :symbol "wk"}}
)

(def om-2
{:bytes 2008552,
 :namespace
 "http://www.ontology-of-units-of-measure.org/resource/om-2/",
 :sha256
 "74b1d65d502852de80be6d71ce1603de686c8807228d5319fadc15e71d040b6e",
 :source
 "https://raw.githubusercontent.com/HajoRijgersberg/OM/master/om-2.0.rdf",
 :verified-at "2026-08-15",
 :verified-by
 "every :om-2 name below matched about=\"&om;<name>\" in that file",
 :website-status
 "500 / 404 on 2026-08-15 — the IRIs are identifiers, not live pages"}
)

;; alias -> canonical, precomputed so lookup is not a scan
(def alias-index
{:EN :en,
 :EUR :eur,
 :JPY :jpy,
 :USD :usd,
 :day :day,
 :days :day,
 :dimensionless :ratio,
 :dollar :usd,
 :ea :each,
 :each :each,
 :en :en,
 :eur :eur,
 :euro :eur,
 :g :g,
 :gram :g,
 :grams :g,
 :h :hour,
 :hour :hour,
 :hours :hour,
 :hr :hour,
 :hrs :hour,
 :jpy :jpy,
 :kg :kg,
 :kgs :kg,
 :kilogram :kg,
 :kilograms :kg,
 :l :litre,
 :liter :litre,
 :liters :litre,
 :litre :litre,
 :litres :litre,
 :m :metre,
 :meter :metre,
 :meters :metre,
 :metre :metre,
 :metres :metre,
 :metric-ton :t,
 :min :minute,
 :minute :minute,
 :minutes :minute,
 :one :ratio,
 :pcs :each,
 :pct :percent,
 :percent :percent,
 :piece :each,
 :pieces :each,
 :ratio :ratio,
 :s :second,
 :sec :second,
 :second :second,
 :seconds :second,
 :t :t,
 :tonne :t,
 :tonnes :t,
 :unit :each,
 :units :each, 
 :usd :usd, 
 :week :week, 
 :weeks :week, 
 :yen :jpy}
)
